<?php

namespace HomeConstruct\BuildBundle\Repository;

use HomeConstruct\BuildBundle\Entity\AppuisFenetre;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * AppuisFenetreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppuisFenetreRepository extends \Doctrine\ORM\EntityRepository
{
}
