<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * ArbreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArbreRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByElagageArbre($elagageArbre){
        $qb = $this->createQueryBuilder('a')
            ->andWhere('a.elagageArbre = :elagageArbre')
            ->setParameter('elagageArbre', $elagageArbre)
            ->getQuery();
        return $qb;
    }
}
