<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * AssainissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssainissementRepository extends \Doctrine\ORM\EntityRepository
{
}
