<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * ChauffageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChauffageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findChauffageExiste($type, $secondOeuvre)
    {
        return $this->createQueryBuilder('mi')
            ->leftJoin('mi.type', 't')
            ->andWhere('mi.type = :type')
            ->andWhere('mi.secondOeuvre = :secondOeuvre')
            ->setParameters(['type' => $type, 'secondOeuvre' => $secondOeuvre])
            ->getQuery()
            ->getOneOrNullResult();
    }
}
