<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * CloisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CloisonRepository extends \Doctrine\ORM\EntityRepository
{
}
