<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * DimensionMenuiserieInterieureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DimensionMenuiserieInterieureRepository extends \Doctrine\ORM\EntityRepository
{
}
