<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * DimensionMenuiserieExterieureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DimensionMenuiserieExterieureRepository extends \Doctrine\ORM\EntityRepository
{
}
