<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * DomotiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomotiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
