<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * ElagageArbreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElagageArbreRepository extends \Doctrine\ORM\EntityRepository
{
}
