<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * EnduitExterieurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnduitExterieurRepository extends \Doctrine\ORM\EntityRepository
{
}
