<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * EscalierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EscalierRepository extends \Doctrine\ORM\EntityRepository
{
}
