<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * EtudeSolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudeSolRepository extends \Doctrine\ORM\EntityRepository
{
}
