<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * EvacuationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvacuationRepository extends \Doctrine\ORM\EntityRepository
{
}
