<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * ExcavationTerrassementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvacuationTerrassementRepository  extends \Doctrine\ORM\EntityRepository
{
}
