<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * FondationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FondationRepository extends \Doctrine\ORM\EntityRepository
{
}
