<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * FormeCharpenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormeCharpenteRepository extends \Doctrine\ORM\EntityRepository
{
}
