<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * FourchetteValeurProfondeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FourchetteValeurProfondeurRepository extends \Doctrine\ORM\EntityRepository
{
}
