<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * GrosOeuvreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrosOeuvreRepository extends \Doctrine\ORM\EntityRepository
{
    function getGrosOeuvresByUser($user){
        $userProjects=$this->getEntityManager()
            ->getRepository('HomeConstructBuildBundle:Projet')
            ->getProjectsByUser($user);
        $userGrosOeuvres=array();
        $j=0;
        foreach ($userProjects as $projet){
            if(in_array($user,$projet->getUsers()->toArray())){
                if($projet->getGrosOeuvre())
                    $userGrosOeuvres[$j]=$projet->getGrosOeuvre();
                $j++;
            }
        }
        return $userGrosOeuvres;
    }
}
