<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * InformationBaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationBaseRepository extends \Doctrine\ORM\EntityRepository
{
}
