<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * IsolationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IsolationRepository extends \Doctrine\ORM\EntityRepository
{
}
