<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * MateriauxMenuiserieExterieureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MateriauxMenuiserieExterieureRepository extends \Doctrine\ORM\EntityRepository
{
}
