<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * MaterielExcavationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterielExcavationRepository extends \Doctrine\ORM\EntityRepository
{
}
