<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * MateriauxMenuiserieInterieureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MateriauxMenuiserieInterieureRepository extends \Doctrine\ORM\EntityRepository
{
}
