<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * MateriauxEscalierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MateriauxEscalierRepository extends \Doctrine\ORM\EntityRepository
{
}
