<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * MenuiserieExterieureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuiserieExterieureRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMenuiserieExiste($type, $materiaux, $largeur, $longueur, $grosOeuvre)
    {
        return $this->createQueryBuilder('me')
            ->leftJoin('me.dimension', 'd')
            ->leftJoin('me.type', 't')
            ->leftJoin('mi.materiaux', 'ma')
            ->where('me.longueur=:longueur')
            ->andWhere('me.largeur = :largeur')
            ->andWhere('me.type = :type')
            ->andWhere('me.materiaux = :materiaux')
            ->andWhere('me.grosOeuvre = :secondOeuvre')
            ->setParameters(['largeur' => $largeur, 'longueur' => $longueur, 'type' => $type, 'materiaux' => $materiaux, 'grosOeuvre' => $grosOeuvre])
            ->getQuery()
            ->getOneOrNullResult();
    }
}
