<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * MenuiserieInterieureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuiserieInterieureRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMenuiserieExiste($type, $materiaux, $largeur, $longueur, $secondOeuvre)
    {
        return $this->createQueryBuilder('mi')
            ->leftJoin('mi.dimension', 'd')
            ->leftJoin('mi.type', 't')
            ->leftJoin('mi.materiaux', 'ma')
            ->where('d.longueur=:longueur')
            ->andWhere('d.largeur = :largeur')
            ->andWhere('mi.type = :type')
            ->andWhere('mi.materiaux = :materiaux')
            ->andWhere('mi.secondOeuvre = :secondOeuvre')
            ->setParameters(['largeur' => $largeur, 'longueur' => $longueur, 'type' => $type, 'materiaux' => $materiaux, 'secondOeuvre' => $secondOeuvre])
            ->getQuery()
            ->getOneOrNullResult();
    }
}
