<?php

/*namespace HomeConstruct\BuildBundle\Repository;

use HomeConstruct\BuildBundle\Entity\Mur;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * @method Mur|null find($id, $lockMode = null, $lockVersion = null)
 * @method Mur|null findOneBy(array $criteria, array $orderBy = null)
 * @method Mur[]    findAll()
 * @method Mur[]    findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
/*class MurRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Mur::class);
    }

    // /**
    //  * @return Mur[] Returns an array of Mur objects
    //  */
    /*
    public function findByExampleField($value)
    {
        return $this->createQueryBuilder('m')
            ->andWhere('m.exampleField = :val')
            ->setParameter('val', $value)
            ->orderBy('m.id', 'ASC')
            ->setMaxResults(10)
            ->getQuery()
            ->getResult()
        ;
    }
    */

    /*
    public function findOneBySomeField($value): ?Mur
    {
        return $this->createQueryBuilder('m')
            ->andWhere('m.exampleField = :val')
            ->setParameter('val', $value)
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }

}*/

namespace HomeConstruct\BuildBundle\Repository;

/**
 * MurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MurRepository extends \Doctrine\ORM\EntityRepository
{
}
