<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * ExcavationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlancherRepository extends \Doctrine\ORM\EntityRepository
{
}
