<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * PlomberieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlomberieRepository extends \Doctrine\ORM\EntityRepository
{
}
