<?php

namespace HomeConstruct\BuildBundle\Repository;

use HomeConstruct\BuildBundle\Entity\Poutre;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * PoutreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoutreRepository extends \Doctrine\ORM\EntityRepository
{
}