<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * PrepaAccesTerrainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrepaAccesTerrainRepository extends \Doctrine\ORM\EntityRepository
{
}
