<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * ProfondeurRecommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfondeurRecommandeRepository extends \Doctrine\ORM\EntityRepository
{
}
