<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends \Doctrine\ORM\EntityRepository
{
    function getProjectsWithoutArchive($projets){
        $etatArchive=$this
            ->getEntityManager()
            ->getRepository('HomeConstructBuildBundle:EtatProjet')
            ->findOneBy(['nom'=>'Archivé']);

        $projetsSansArchive=array();
        $j=0;
        foreach($projets as $projet){
            if($projet->getEtat()!=$etatArchive){
                $projetsSansArchive[$j]=$projet;
                $j++;
            }
        }
        return $projetsSansArchive;
    }

    function getProjectsByUser($user){
        $projets=$this->getEntityManager()
            ->getRepository('HomeConstructBuildBundle:Projet')
            ->findAll();
        $usersProjects=array();
        $j=0;
        foreach ($projets as $projet){
            if(in_array($user,$projet->getUsers()->toArray())){
                $usersProjects[$j]=$projet;
                $j++;
            }
        }
        return $usersProjects;
    }

    function getProjectsByEtatAndUser($user,$etat)
    {
        $projets=$this->getEntityManager()
            ->getRepository('HomeConstructBuildBundle:Projet')
            ->findAll();
        $projectsWithThisEtat=array();
        $j=0;
        foreach ($projets as $projet){
            if($projet->getEtat()==$etat && in_array($user,$projet->getUsers()->toArray())){
                $projectsWithThisEtat[$j]=$projet;
                $j++;
            }
        }
        return $projectsWithThisEtat;
    }

}
