<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * ReseauEauPotableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReseauEauPotableRepository extends \Doctrine\ORM\EntityRepository
{
}
