<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * ReseauGazNaturelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReseauGazNaturelRepository extends \Doctrine\ORM\EntityRepository
{
}
