<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * ReseauElectriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReseauElectriqueRepository extends \Doctrine\ORM\EntityRepository
{
}
