<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * ReseauEauUseeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReseauEauUseeRepository extends \Doctrine\ORM\EntityRepository
{
}
