<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * RevetementSolPieceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RevetementSolPieceRepository extends \Doctrine\ORM\EntityRepository
{
}
