<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * RevetementToitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RevetementToitureRepository extends \Doctrine\ORM\EntityRepository
{
}
