<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * SecondOeuvreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecondOeuvreRepository extends \Doctrine\ORM\EntityRepository
{
}
