<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * SoubassementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoubassementRepository extends \Doctrine\ORM\EntityRepository
{
}
