<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * TailleArbreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TailleArbreRepository extends \Doctrine\ORM\EntityRepository
{
}
