<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * TarifArbreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifArbreRepository extends \Doctrine\ORM\EntityRepository
{
}
