<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * TerrassementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TerrassementRepository extends \Doctrine\ORM\EntityRepository
{
}
