<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * ToitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ToitureRepository extends \Doctrine\ORM\EntityRepository
{
}
