<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * TravauxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravauxRepository extends \Doctrine\ORM\EntityRepository
{
}
