<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * TypeChauffageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeChauffageRepository extends \Doctrine\ORM\EntityRepository
{

}
