<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * TypeIsolationPlafondRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeIsolationPlafondRepository extends \Doctrine\ORM\EntityRepository
{
}
