<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * TypeSolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeSolRepository extends \Doctrine\ORM\EntityRepository
{
}
