<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * TypeVentilationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeVentilationRepository extends \Doctrine\ORM\EntityRepository
{
}
