<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * TypePlomberieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypePlomberieRepository extends \Doctrine\ORM\EntityRepository
{
}
