<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * TypeRevetementSolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeRevetementSolRepository extends \Doctrine\ORM\EntityRepository
{
}
