<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * TypeEvacuationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeEvacuationRepository extends \Doctrine\ORM\EntityRepository
{
}
