<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * TypeCharpenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeCharpenteRepository extends \Doctrine\ORM\EntityRepository
{
}
