<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * TypeCouvertureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeCouvertureRepository extends \Doctrine\ORM\EntityRepository
{
}
