<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * TypeIsolationPlancherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeIsolationPlancherRepository extends \Doctrine\ORM\EntityRepository
{
}
