<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * TypeFondationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeFondationRepository extends \Doctrine\ORM\EntityRepository
{
}
