<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * TypeFerraillageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeFerraillageRepository extends \Doctrine\ORM\EntityRepository
{
}
