<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * TypeSoubassementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeSoubassementRepository extends \Doctrine\ORM\EntityRepository
{
}
