<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * TypeIsolationPieceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeIsolationPieceRepository extends \Doctrine\ORM\EntityRepository
{
}
