<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * TypeTerrassementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeTerrassementRepository extends \Doctrine\ORM\EntityRepository
{
}
