<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * TypeMenuiserieExterieureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeMenuiserieExterieureRepository extends \Doctrine\ORM\EntityRepository
{
}
