<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * TypeIsolationVitreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeIsolationVitreRepository extends \Doctrine\ORM\EntityRepository
{
}
