<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * TypeMenuiserieInterieureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeMenuiserieInterieureRepository extends \Doctrine\ORM\EntityRepository
{
}
