<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * TypeClimatisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeClimatisationRepository extends \Doctrine\ORM\EntityRepository
{

}
