<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * TypeIsolationMurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeIsolationMurRepository extends \Doctrine\ORM\EntityRepository
{
}
