<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * TypeArbreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeArbreRepository extends \Doctrine\ORM\EntityRepository
{
}
