<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * TypeEnduitExterieurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeEnduitExterieurRepository extends \Doctrine\ORM\EntityRepository
{
}
