<?php

namespace HomeConstruct\BuildBundle\Repository;

/**
 * MateriauxDomotiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeDomotiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
